### ISSUE TITLE
Extracción de conceptos: "Ceremonias"

### ISSUE THREAD

**Issue by Loreaylen** [Loreaylen/Proyecto-de-Grupo-de-Estudio-Aula-10#1]
- Extraer del material de Scrum el concepto: _ceremonias_
- Añadir  concepto al README (conceptosscrum)

**Comment by Luu089** [comment]
Ceremonias ya está completo

**Comment by Loreaylen** [comment]
Perfecto, muevan la card en el proyecto a la columna "done". Buen trabajo.

**Comment by HernanRT** [comment]
Ceremonias completo
